services:
  postgres:
    image: postgres:15-alpine
    network_mode: host
    restart: "always"
    environment:
      # Superuser username/password
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./postgres-firstrun/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro"

  redis:
    image: redis:7
    network_mode: host
    volumes:
      - "./redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: "always"
    command: 'redis-server --save 60 1 --loglevel warning'
