name: "telegram-feedback-bot-topics"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    # Use your credentials here
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: feedback_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      - CONFIG_FILE_PATH=/app/settings.toml
    # Make sure to create settings.toml with necessary config parameters.
    # Also copy any language file and place it in the root of your project.
    volumes:
      - "./settings.toml:/app/settings.toml:ro"
      - "./ru.ftl:/app/bot/locale/current/strings.ftl:ro"
    depends_on:
      - postgres


  migrations:
    profiles:
      - "migrate"
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      - CONFIG_FILE_PATH=/app/settings.toml
    volumes:
      - "./settings.toml:/app/settings.toml:ro"
    depends_on:
      - postgres
    command: ["-m", "alembic", "upgrade", "head"]


volumes:
  postgres_data: