version: '3.1'

services:
  postgres:
    image: postgres:17-alpine
    restart: "always"
    environment:
      # Superuser username/password
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./postgres-firstrun/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro"
