#### Bot-specific settings ####
[bot]
  # Bot's token. Obtain from https://t.me/BotFather
token = "1234567890:AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTt"

[logs]
show_datetime = true
datetime_format = "%Y-%m-%d %H:%M:%S"
show_debug_logs = true
time_in_utc = false
use_colors_in_console = true
renderer = "console"
