"""Added bans table

Revision ID: 002
Revises: 001
Create Date: 2023-10-07 21:57:09.476157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('is_banned', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('is_shadowbanned', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bans')
    # ### end Alembic commands ###
